# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
name: cluster
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
